version: "3"
services:
  cybertron-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd4postgres
    ports:
      - 5432:5432
    container_name: cybertron-db
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - skynet
networks:
  skynet:
    driver: bridge
